import { englishCourse } from "@/data/courses/english-course";
import assert from "node:assert/strict";
import { getCourseNodeAccess } from "@/lib/courses/course-access";
import { createDefaultCourseProgress } from "@/lib/courses/course-progress";
import { applyPlacementUnlock, completeCourseNode, } from "@/lib/courses/course-unlock-policy";
const initial = createDefaultCourseProgress(englishCourse);
assert.equal(getCourseNodeAccess(initial, "lesson-1", englishCourse).allowed, true);
assert.equal(getCourseNodeAccess(initial, "lesson-2", englishCourse).reason, "locked-node");
assert.equal(getCourseNodeAccess(initial, "en-s2-c1-lesson-1", englishCourse).reason, "locked-section");
assert.equal(getCourseNodeAccess(initial, "unknown-node", englishCourse).reason, "not-found");
const afterLessonOne = completeCourseNode(initial, "lesson-1", englishCourse).progress;
assert.equal(getCourseNodeAccess(afterLessonOne, "lesson-2", englishCourse).allowed, true);
const sectionTwo = applyPlacementUnlock(initial, "english-section-2", englishCourse);
assert.equal(getCourseNodeAccess(sectionTwo, "en-s2-c1-lesson-1", englishCourse).allowed, true);
assert.equal(getCourseNodeAccess(sectionTwo, "en-s2-c1-lesson-2", englishCourse).reason, "locked-node");
console.log("Course access check passed: section locks, node prerequisites, unknown ids, and first-node access are enforced.");
